# Generated by Django 3.2.2 on 2021-05-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='email',
            field=models.EmailField(default=3, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
    ]
