# Generated by Django 3.2.2 on 2021-05-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_test_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
